WIP add upload to storj flow
yral-dapp/off-chain-agent pull request #102
Opened 2024-12-09 17:15 UTC by tushar-saxena-yral

2024-12-16 14:57 UTC, psykomal requested changes
small change suggestion. 

Also make sure the pipeline is running end2end in preview by uploading video in ssr
make sure these happen :- 
- video getting added to storj (I know you tested this, but is it also tested after secrets got added ?)
- video getting added to google cloud storage  (ask Saikat to add in our google project) - yral-videos bucket name
- video nsfw details getting inserted in nsfw table - table name :  hot-or-not-feed-intelligence.yral_ds.video_nsfw

2024-12-16 15:33 UTC, tushar-saxena-yral commented on src/consts.rs
> +    Lazy::new(|| Url::parse("https://pr-102-yral-dapp-off-chain-agent.fly.dev/").unwrap());
will revert back once at the very end, once i have tested with the creds that saikat provides

2024-12-16 15:33 UTC, tushar-saxena-yral commented on src/events/nsfw.rs
> -#[cfg(not(feature = "local-bin"))]
oh it is, i will add this back. removed it cuz it was messing with my lsp kek

2024-12-16 15:37 UTC, tushar-saxena-yral commented on .github/workflows/deploy-on-merge-to-main.yml
> +          STORJ_GATEWAY_URL: ${{ secrets.STORJ_GATEWAY_URL }}
makes sense, but how will they reach the fly machine? im sorry im not too familiar with secrets in github ci/cd

2024-12-16 15:40 UTC, tushar-saxena-yral commented
> * video getting added to storj (I know you tested this, but is it also tested after secrets got added ?)

i have tested this with my creds added as secrets.

> * video getting added to google cloud storage

that's a really good concern, will confirm with saikat

2024-12-16 15:54 UTC, komal-sai-yral commented on .github/workflows/deploy-on-merge-to-main.yml
> +          STORJ_GATEWAY_URL: ${{ secrets.STORJ_GATEWAY_URL }}
depends on whether Saikat embedded them as secrets or env vars. once check with him 

if it is env var, use it like this https://github.com/yral-dapp/nsfw_detect/blob/0dd87313f80d86d0df797e874d3c608f2bd1e9c3/.github/workflows/deploy-on-merge-to-main.yml#L33

2024-12-16 15:57 UTC, komal-sai-yral commented on .github/workflows/deploy-on-merge-to-main.yml
> +          STORJ_GATEWAY_URL: ${{ secrets.STORJ_GATEWAY_URL }}
as to how they get added to fly env vars, its due to the cmd above these lines : flyctl secrets set

2024-12-17 12:54 UTC, tushar-saxena-yral commented
@komal-sai-yral so i believe there are no more code changes required, only testing with real creds once and making sure:
- storj upload works
- gcp upload isn't broken
- nsfw detection isn't broken

@saikat-das-yral cc

2024-12-23 13:25 UTC, tushar-saxena-yral commented
@saikat-das-yral
We need the following details for accessing the gateway. 
```bash
          STORJ_ACCESS_KEY_ID # can be an env var
          STORJ_SECRET_KEY # must be a secret
          STORJ_GATEWAY_URL # can be an env var
```

To self host the gateway you can follow the guide [here](https://storj.dev/learn/self-host/gateway-st).

Tldr:
- Create an account on storj
- Create an access grant
- Setup the gateway with storj's satellite (or host your own satellite https://storj.dev/learn/concepts/satellite)
- The access key and secret key will be outputted by the gateway program (https://storj.dev/learn/self-host/gateway-st#run-gateway-st)

## On hosting your own satellite
While it is possible to host your own satellite, it is a big can of worms. But here's some reference material:
- Announcement: https://forum.storj.io/t/announcing-community-satellite-pilot-program/21666
- https://forum.storj.io/t/how-to-run-a-satellite-node/26158/2

2025-01-28 08:08 UTC, closed without merging